### ISSUE TITLE
OpenBSD-latest is out of date

### ISSUE THREAD

**Issue by tobhe** [mario-campos/emulate#12]
I noticed that when running the CI it tries fetching packages for OpenBSD 7.1 from the mirror which are no longer available since it is out of support now that 7.3 is out.

It would be nice if you could update -latest to 7.3.

**Comment by mario-campos** [comment]
@tobhe, yeah, of course. Apologies for the terrible delay. I haven't touched this project in a bit, but it's long overdue.

**Comment by tobhe** [comment]
No worries, thanks for the quick response :) I saw @jimh-gh is already working on a fix in https://github.com/mario-campos/emulate/pull/13

**Comment by mario-campos** [comment]
Yeah, indeed! I merged #13, but I'm having a bit of trouble with Packer and building the image. Once I get that sorted out, I'll upload it and close this, so you know.

**Comment by mario-campos** [comment]
New images uploaded :)
